.*: Assembler messages:
.*: Error: shift amount must be in the range 0\.\.63
.*: Error: shift amount must be in the range 0\.\.63
.*: Error: shift amount must be in the range 0\.\.63
.*: Error: shift amount must be in the range 0\.\.63
.*: Error: shift amount must be in the range 0\.\.63
.*: Error: shift amount must be in the range 0\.\.63
.*: Error: shift amount must be in the range 0\.\.63
.*: Error: shift amount must be in the range 0\.\.63
